import fs from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { Presentation, PresentationFile } from '@oai/artifact-tool';

const workspaceDir = process.cwd();
const SKILL_DIR = 'C:/Users/Mx/.codex/plugins/cache/openai-primary-runtime/presentations/26.905.11957/skills/presentations';
const TMP_DIR = path.join(workspaceDir, '.deck_build');
const FINAL_PPTX = path.join(workspaceDir, 'deliverables', 'VenueFit_Boston_Presentation.pptx');
await fs.mkdir(TMP_DIR,{recursive:true});
const { resolvePresentationFont, applyPresentationChartFont, finalizePresentation } = await import(pathToFileURL(path.join(SKILL_DIR,'container_tools/artifact_tool_utils.mjs')).href);
const font = resolvePresentationFont();
const p = Presentation.create({slideSize:{width:1280,height:720}});
const C={ink:'#102726',mid:'#456260',lime:'#D7F55A',teal:'#54C6B4',paper:'#F6F7F4',coral:'#F58662',line:'#D9E3DF',white:'#FFFFFF'};
function box(slide,text,left,top,width,height,size=20,color=C.ink,bold=false){const s=slide.shapes.add({geometry:'textbox',position:{left,top,width,height},fill:'none',line:{fill:'none',width:0}});s.text=text;s.text.style={typeface:font,fontSize:size,bold,color,autoFit:'shrinkText'};return s}
function base(slide,num){slide.background.fill=C.paper;box(slide,'VENUEFIT BOSTON',66,38,260,20,11,C.mid,true);box(slide,String(num).padStart(2,'0'),1165,38,46,20,11,C.mid,true)}
function title(slide,text,sub){box(slide,text,66,86,1080,86,38,C.ink,true);if(sub)box(slide,sub,68,180,990,50,16,C.mid,false)}
function note(slide,text){slide.speakerNotes.textFrame.setText(text)}
function divider(slide){const s=slide.shapes.add({geometry:'rect',position:{left:66,top:244,width:1148,height:2},fill:C.line,line:{fill:'none',width:0}})}
function metric(slide,label,value,left,top){box(slide,label.toUpperCase(),left,top,220,18,10,C.mid,true);box(slide,value,left,top+24,230,42,28,C.ink,true)}

{const s=p.slides.add();s.background.fill=C.ink;box(s,'VENUEFIT',68,58,200,20,12,C.lime,true);box(s,'Boston venue planning\nwith public data',68,160,770,150,54,C.white,true);box(s,'A five-minute decision-tool demonstration',71,336,500,32,18,'#D7E3DB');box(s,'Capacity  •  setting  •  transit proximity',71,600,620,22,12,C.lime,true);box(s,'17 SEPTEMBER 2026',1035,600,180,22,11,'#D7E3DB',true);note(s,'Sources: venue-owner pages, City of Boston public project material, and MBTA GTFS documentation. Full links appear in the site and CSV.');}
{const s=p.slides.add();base(s,2);title(s,'The decision problem','Event teams need a fast, defensible way to create a first venue shortlist.');divider(s);box(s,'INTENDED USERS',68,282,230,18,11,C.mid,true);box(s,'University event offices, nonprofit producers, and local community organizers planning public events in Boston.',68,313,410,116,20,C.ink,true);box(s,'THE QUESTION',642,282,210,18,11,C.mid,true);box(s,'Which venue can fit the audience while keeping rapid-transit access practical?',642,313,430,85,24,C.ink,true);metric(s,'Venues compared','8',68,520);metric(s,'Key filters','4',330,520);metric(s,'Personal data','None',592,520);note(s,'Decision framing created for the course challenge. The tool is a comparison aid, not a booking or attendance prediction system.');}
{const s=p.slides.add();base(s,3);title(s,'A small, documented comparison set','Every row retains a capacity source and source-access date in the downloadable CSV.');const chart=s.charts.add('bar',{position:{left:70,top:265,width:700,height:350},categories:['Agganis Arena','MGM Music Hall','Leader Bank Pavilion','Roadrunner','Wang Theatre','House of Blues','Shubert Theatre','Jordan Hall'],series:[{name:'Maximum capacity',values:[7500,5000,5000,3500,3500,2200,1500,1019],fill:C.teal}],barOptions:{direction:'bar',grouping:'clustered'},hasLegend:false,dataLabels:{showValue:true,position:'outEnd'}});applyPresentationChartFont(chart,{fontFamily:font});box(s,'WHAT WE COLLECTED',850,280,250,18,11,C.mid,true);box(s,'Published maximum capacity',850,312,275,35,19,C.ink,true);box(s,'Indoor or outdoor setting',850,365,275,35,19,C.ink,true);box(s,'Operating season',850,418,275,35,19,C.ink,true);box(s,'Nearest rapid-transit stop and an approximate straight-line distance',850,471,300,65,19,C.ink,true);note(s,'Sources: Agganis Arena Capacity and Specifications; City of Boston MGM Music Hall project presentation; Leader Bank Pavilion information; Roadrunner rental information; Boch Center spaces; House of Blues Boston event sheet; NEC Jordan Hall. Accessed 17 September 2026.');}
{const s=p.slides.add();base(s,4);title(s,'The site turns a brief into a shortlist','Users change expected attendance, setting, season, and transit tolerance.');divider(s);metric(s,'Example attendance','2,500',68,285);metric(s,'Default ticket test','$125k',365,285);metric(s,'Transit tolerance','600 m',660,285);box(s,'SCORING LOGIC',68,415,180,18,11,C.mid,true);box(s,'60 points for capacity fit. Up to 30 points for transit proximity. 10 points for preferred setting.',68,445,440,76,19,C.ink,true);box(s,'EXAMPLE RESULT',640,415,180,18,11,C.mid,true);box(s,'Wang Theatre ranks first for the default brief, followed by Roadrunner. Both are indoor, seat 3,500, and sit within 500 m of rapid transit.',640,445,460,90,19,C.ink,true);box(s,'The $50 ticket figure is an illustrative planning input. It is not a claim about venue pricing or demand.',68,618,800,20,11,C.mid,false);note(s,'Site calculation definition: score = capacity-fit component (0 to 60) + transit-proximity component (0 to 30) + setting-match component (0 or 10). Ticket revenue is attendees multiplied by a user-visible $50 illustrative input.');}
{const s=p.slides.add();base(s,5);title(s,'What the comparison supports','The data identifies viable first checks, not final booking decisions.');divider(s);box(s,'1',70,282,40,38,30,C.teal,true);box(s,'For 2,000–3,500-person indoor events, start with Roadrunner and Wang Theatre.',132,278,900,42,23,C.ink,true);box(s,'Both meet the scale threshold and lie within 500 meters of rapid transit.',132,327,840,28,15,C.mid,false);box(s,'2',70,410,40,38,30,C.coral,true);box(s,'For 5,000-seat summer events, evaluate Leader Bank Pavilion with a weather and access plan.',132,406,935,42,23,C.ink,true);box(s,'Its outdoor seasonal format and 930-meter transit proxy make those risks explicit.',132,455,840,28,15,C.mid,false);box(s,'3',70,538,40,38,30,C.lime,true);box(s,'For 1,000–1,500 seated events, check Jordan Hall or Shubert Theatre before scaling up.',132,534,940,42,23,C.ink,true);box(s,'Right-sizing is a planning hypothesis. Confirm configuration and cost with the venue.',132,583,840,28,15,C.mid,false);note(s,'Recommendations are derived from capacities and transit-distance proxy in venues.csv. They do not claim causal effects on satisfaction, cost, ticket sales, or attendance.');}
{const s=p.slides.add();base(s,6);title(s,'Limits keep the decision honest','The tool makes a transparent first shortlist and defines what needs follow-up.');divider(s);box(s,'WHAT THE DATA SUPPORTS',68,285,320,18,11,C.mid,true);box(s,'A repeatable comparison of venue scale, setting, season, and approximate transit proximity.',68,317,420,94,21,C.ink,true);box(s,'WHAT IT CANNOT PROVE',640,285,320,18,11,C.mid,true);box(s,'Availability, price, demand, satisfaction, walking time, accessibility, weather, production feasibility, or neighborhood impact.',640,317,460,94,21,C.ink,true);box(s,'Next step: confirm event configuration, route and service conditions, accessibility provisions, date availability, and a quote with each shortlisted venue.',68,536,1015,44,19,C.ink,true);box(s,'Data, methodology note, reflection, and source links accompany the site.',68,608,700,20,12,C.mid,false);note(s,'Limitations: capacities vary by configuration; transit distance is straight-line, not walking time; sample has eight venues and is not a market census; data excludes availability, quotes, satisfaction, and individual attendee data.');}

const candidatePath=path.join(workspaceDir,'.codex-finalizer','venuefit_candidate.pptx');await fs.mkdir(path.dirname(candidatePath),{recursive:true});await (await PresentationFile.exportPptx(p)).save(candidatePath);
await fs.mkdir(path.dirname(FINAL_PPTX),{recursive:true});
const requirements={explicitTotalSlideCount:6,requiredNativeTableOwnerSlides:[],requiredNativeChartOwnerSlides:[]};
await finalizePresentation({ ...requirements,workspaceDir,candidatePath,finalPath:FINAL_PPTX,pythonExecutable:'C:/Users/Mx/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe',integrityValidatorPath:path.join(SKILL_DIR,'container_tools/inspect_presentation_package_integrity.py'),layoutValidatorPath:path.join(SKILL_DIR,'container_tools/inspect_presentation_layout_geometry.py'),layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-bullet-geometry','--validate-heading-fit'],fontPolicy:{basis:'design',families:[font]},materializeLiteralChartWorkbooks:true,verifyArtifactToolImport:true,receiptPath:path.join(workspaceDir,'.codex-finalizer','VenueFit_Boston_Presentation.validation.json')});
console.log(FINAL_PPTX);
